name: pyhgf_dev
dependencies:
  - python=3.12
  - pip
  - conda-forge::pymc
  - graphviz
  - pip:
    - jax==0.4.26
    - jaxlib==0.4.26
    - numpy==1.26.4
    - matplotlib>=3.0.2
    - seaborn>=0.9.0
    - arviz>=0.18.0
    - setuptools>=69.5.1
    - packaging
    - pytest
    - pre-commit