name: Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Build
        run: |
          sudo apt-get install graphviz
          pip install -r requirements-docs.txt
          sphinx-build -j 4 -T -b html docs/source docs/build/html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/build/html
          BRANCH: gh-pages
